version: '3'
services:
  web-server:
    image: php:7.4.3-apache
    volumes:
        - "./html/:/var/www/html/"
    ports:
        - "8080:80"

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=mongodb_database

  neo4j:
    image: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - neo4j_data:/data

  mysql-odb-server:
    image: mysql:8.0.19
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mysql-data:/var/lib/mysql_odb
    ports:
      - "13306:3306"
      
  mysql-dw-server:
    image: mysql:8.0.19
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mysql-data:/var/lib/mysql_dw
    ports:
      - "23306:3306"

  phpmyadmin-odb:
    image: phpmyadmin/phpmyadmin:5.0.1
    environment:
      PMA_HOST: mysql-odb-server
      PMA_USER: root
      PMA_PASSWORD: secret
    ports:
        - "15000:80"
        
  phpmyadmin-dw:
    image: phpmyadmin/phpmyadmin:5.0.1
    environment:
      PMA_HOST: mysql-dw-server
      PMA_USER: root
      PMA_PASSWORD: secret
    ports:
        - "25000:80"
volumes:
  mongodb_data:
  neo4j_data:
  mysql-data:
